### ISSUE TITLE
Migrate the comparison ARD and regression ARD functions to {cardx}

### ISSUE THREAD

**Issue by ddsjoberg** [insightsengineering/cards#143]
- [x] `ard_fishertest()`
    - [x] add to {cardx} @ddsjoberg https://github.com/insightsengineering/cardx/pull/21
    - [x] remove from {cards} @ddsjoberg #147 
- [x] `ard_wilcox()`, add `ard_paired_wilcox()` at the same time. Can be modeled after `ard_ttest()` and `ard_paired_ttest()`
    - [x] add to {cardx} @ddsjoberg https://github.com/insightsengineering/cardx/pull/25
    - [x] remove from {cards} @ddsjoberg #147 
- [x] `ard_chisqtest()`
    - [x] add to {cardx} @ddsjoberg https://github.com/insightsengineering/cardx/pull/22
    - [x] remove from {cards} @ddsjoberg #147 
- [x] `ard_regression()` I think we may need to make this an S3 generic. There are some model types that may need special structures, the first that comes to mind is multinomial logistic regression.
    - [x] add to {cardx} @ddsjoberg https://github.com/insightsengineering/cardx/pull/26
    - [x] remove from {cards} @ddsjoberg #147 
- [x] remember to remove the package deps from cards! @ddsjoberg #147
